"""
Registry of Australian Whole-of-Government agencies involved in CBRN & Pandemic Response.
Includes statutory mandates, direct legislation links, and jurisdiction mappings.
"""

from typing import Dict
from ..models.agency import AgencyIdentifier, AgencyProfile

AUSTRALIAN_AGENCIES: Dict[AgencyIdentifier, AgencyProfile] = {
    AgencyIdentifier.ACDP: AgencyProfile(
        id=AgencyIdentifier.ACDP,
        full_name="Australian Centre for Disease Prevention (ACDP)",
        portfolio="Department of Health and Aged Care / CSIRO",
        mandate_summary="Australia's premier high-containment pathogen research and reference facility at Geelong (CSIRO ACDP), providing national diagnostic confirmation, PC4 physical containment, and zoonotic disease surveillance.",
        key_responsibilities=[
            "Diagnostic confirmatory testing of unknown viral and bacterial pathogens in PC4 containment",
            "Genomic epidemiology, phylogenetics, and molecular characterization",
            "National risk assessment and public health advice to Chief Medical Officer (CMO)",
            "Liaison with state Public Health Laboratory Network (PHLN) and international reference bodies",
        ],
        statutory_authority="National Health Security Act 2007 (Cth)",
        official_website="https://www.csiro.au/en/about/facilities-collections/acdp",
        legislation_url="https://www.legislation.gov.au/Details/C2021C00122",
        liaison_contact_role="ACDP Director & National High-Containment Diagnostic Lead",
        preferred_brief_format="Epidemiological & Diagnostic Situation Report (SITREP) with genomic confirmation and transmission metrics.",
        relevant_threat_types=["biological_virus", "biological_bacteria", "synthetic_engineered"],
    ),
    AgencyIdentifier.TGA: AgencyProfile(
        id=AgencyIdentifier.TGA,
        full_name="Therapeutic Goods Administration (TGA)",
        portfolio="Department of Health and Aged Care",
        mandate_summary="Evaluating and regulating medicines, vaccines, medical devices, and rapid diagnostic tests for safety, quality, and efficacy.",
        key_responsibilities=[
            "Emergency Use Authorisations (EUA) and Section 19A emergency medicine import exemptions",
            "Expedited scientific evaluation of repurposed antivirals, antidotes, and novel vaccine candidates",
            "Batch testing, GMP release protocols, and cold-chain supply compliance",
            "Post-market safety surveillance and adverse event monitoring (DAEN)",
        ],
        statutory_authority="Therapeutic Goods Act 1989 (Cth)",
        official_website="https://www.tga.gov.au",
        legislation_url="https://www.legislation.gov.au/Details/C2022C00289",
        liaison_contact_role="TGA Medical Countermeasures Regulatory Taskforce Director",
        preferred_brief_format="Regulatory & Medical Countermeasure Readiness Dossier (ARTG status, binding affinity, safety alerts, manufacturing timeline).",
        relevant_threat_types=["biological_virus", "biological_bacteria", "chemical_toxin", "chemical_nerve_agent", "radiological_dispersal", "synthetic_engineered"],
    ),
    AgencyIdentifier.DAFF: AgencyProfile(
        id=AgencyIdentifier.DAFF,
        full_name="Department of Agriculture, Fisheries and Forestry (DAFF Biosecurity)",
        portfolio="Department of Agriculture, Fisheries and Forestry",
        mandate_summary="National border biosecurity, animal and plant health, surveillance of zoonotic spillovers, and agricultural economic protection.",
        key_responsibilities=[
            "Zoonotic spillover surveillance (e.g., Avian Influenza H5N1, Swine Flu, Henipavirus)",
            "Livestock and wildlife containment zones and quarantine movement controls",
            "Border biosecurity risk screening (BICON, air/sea ports of entry)",
            "Liaison with Australian Chief Veterinary Officer (ACVO) and World Organisation for Animal Health (WOAH)",
        ],
        statutory_authority="Biosecurity Act 2015 (Cth)",
        official_website="https://www.agriculture.gov.au/biosecurity-trade",
        legislation_url="https://www.legislation.gov.au/Details/C2021C00424",
        liaison_contact_role="Australian Chief Veterinary Officer (ACVO) & Biosecurity Operations Commander",
        preferred_brief_format="One-Health Zoonotic Alert (Species susceptibility, spillover risk, geographic quarantine bounds, livestock impact).",
        relevant_threat_types=["biological_virus", "biological_bacteria"],
    ),
    AgencyIdentifier.DSTG: AgencyProfile(
        id=AgencyIdentifier.DSTG,
        full_name="Defence Science and Technology Group & Defence CBRN (DSTG)",
        portfolio="Department of Defence",
        mandate_summary="National security science, CBRN defence counter-measures, dual-use pathogen forensics, and sovereign defence readiness.",
        key_responsibilities=[
            "Dual-use research and gain-of-function molecular forensics",
            "Verification of chemical weapon pre-cursor structures under CWC Schedules",
            "Physical and medical CBRN defence equipment compatibility and ADF protection",
            "International technical collaboration via TTCP (Five-Eyes) CBRN Defense Group",
        ],
        statutory_authority="Defence Act 1903 (Cth) & Weapons of Mass Destruction Act 1995 (Cth)",
        official_website="https://www.dst.defence.gov.au",
        legislation_url="https://www.legislation.gov.au/Details/C2016C00843",
        liaison_contact_role="Chief of CBRN Defence Research & Technical Intelligence Directorate",
        preferred_brief_format="CBRN Technical Intelligence Brief (Aerosolization potential, dual-use markers, force health protection recommendations).",
        relevant_threat_types=["chemical_nerve_agent", "chemical_toxin", "synthetic_engineered", "radiological_dispersal"],
    ),
    AgencyIdentifier.NEMA: AgencyProfile(
        id=AgencyIdentifier.NEMA,
        full_name="National Emergency Management Agency (NEMA)",
        portfolio="Department of Home Affairs",
        mandate_summary="Commonwealth disaster and emergency management coordination, National Situation Room (NSR) operation, and civil protection crisis logistics.",
        key_responsibilities=[
            "Coordinating Australian Government Disaster Response Plan (COMDISPLAN)",
            "National Medical Stockpile (NMS) distribution logistics to States and Territories",
            "Real-time situational monitoring via National Situation Room (NSR)",
            "Interstate resource sharing and critical emergency supply chain preservation",
        ],
        statutory_authority="National Emergency Declaration Act 2020 (Cth)",
        official_website="https://www.nema.gov.au",
        legislation_url="https://www.legislation.gov.au/Details/C2020A00128",
        liaison_contact_role="National Situation Room Crisis Coordinator & Logistics Director",
        preferred_brief_format="National Operational SITREP (Logistics impact, supply chain pinch points, resource deployment triggers).",
        relevant_threat_types=["biological_virus", "biological_bacteria", "chemical_nerve_agent", "chemical_toxin", "radiological_dispersal", "synthetic_engineered"],
    ),
    AgencyIdentifier.DFAT: AgencyProfile(
        id=AgencyIdentifier.DFAT,
        full_name="Department of Foreign Affairs and Trade (DFAT)",
        portfolio="Department of Foreign Affairs and Trade",
        mandate_summary="International health security notifications, Indo-Pacific regional assistance, and diplomatic coordination under International Health Regulations (IHR 2005).",
        key_responsibilities=[
            "Official notifications to World Health Organization (WHO) and regional partners",
            "Coordination of consular travel advisories (Smartraveller) and repatriation protocols",
            "Indo-Pacific Centre for Health Security deployment of technical teams",
            "Compliance with Biological Weapons Convention (BWC) and Chemical Weapons Convention (OPCW)",
        ],
        statutory_authority="International Health Regulations 2005 (Cth ratification)",
        official_website="https://www.dfat.gov.au",
        legislation_url="https://www.legislation.gov.au/Details/C2016C00843",
        liaison_contact_role="Ambassador for Regional Health Security & Multilateral Treaties Branch Head",
        preferred_brief_format="Diplomatic & International Notification Telegram (WHO triggers, consular risk rating, bilateral assistance).",
        relevant_threat_types=["biological_virus", "biological_bacteria", "chemical_nerve_agent", "synthetic_engineered"],
    ),
    AgencyIdentifier.CSIRO: AgencyProfile(
        id=AgencyIdentifier.CSIRO,
        full_name="Commonwealth Scientific and Industrial Research Organisation (CSIRO)",
        portfolio="Department of Industry, Science and Resources",
        mandate_summary="Translational scientific research, high-throughput pathogen diagnostics, biomanufacturing scale-up, and therapeutic validation.",
        key_responsibilities=[
            "High-throughput screening and structural biology at Australian Synchrotron",
            "Pre-clinical efficacy testing (in vitro / in vivo animal models)",
            "mRNA and recombinant protein pilot biomanufacturing scale-up",
            "AI-driven protein structure prediction and antiviral computational design",
        ],
        statutory_authority="Science and Industry Research Act 1949 (Cth)",
        official_website="https://www.csiro.au",
        legislation_url="https://www.legislation.gov.au/Details/C2016C00908",
        liaison_contact_role="CSIRO Health and Biosecurity Science Director",
        preferred_brief_format="Translational Science & Biomanufacturing Memo (Structure coordinates, candidate yields, assay results).",
        relevant_threat_types=["biological_virus", "biological_bacteria", "chemical_toxin", "synthetic_engineered"],
    ),
    AgencyIdentifier.OGTR: AgencyProfile(
        id=AgencyIdentifier.OGTR,
        full_name="Office of the Gene Technology Regulator (OGTR)",
        portfolio="Department of Health and Aged Care",
        mandate_summary="Regulating genetically modified organisms (GMOs) and synthetic biology to protect public health and the Australian environment.",
        key_responsibilities=[
            "Emergency dealing determinations for novel engineered viral vectors and GMO vaccines",
            "Containment level certification (PC2, PC3, PC4) for synthetic biology facilities",
            "Dual-use synthetic genomics risk evaluation and gain-of-function biosafety",
            "Enforcement of gene editing regulatory standards under National Gene Technology Scheme",
        ],
        statutory_authority="Gene Technology Act 2000 (Cth)",
        official_website="https://www.ogtr.gov.au",
        legislation_url="https://www.legislation.gov.au/Details/C2021C00201",
        liaison_contact_role="Gene Technology Regulator & Evaluation Branch Head",
        preferred_brief_format="Biosafety & Synthetic Genetics Regulatory Notice (Genetic modification assessment, containment level certification).",
        relevant_threat_types=["synthetic_engineered", "biological_virus"],
    ),
    AgencyIdentifier.ARPANSA: AgencyProfile(
        id=AgencyIdentifier.ARPANSA,
        full_name="Australian Radiation Protection and Nuclear Safety Agency (ARPANSA)",
        portfolio="Department of Health and Aged Care",
        mandate_summary="Australian Government primary authority on radiation protection and nuclear safety. Regulates radiological emergencies and public health intervention doses.",
        key_responsibilities=[
            "National Radiation Monitoring Network (ARMN) gamma-spectrometry surveillance",
            "Emergency Reference Level (ERL) dose assessment under Radiation Protection Series C-1",
            "Atmospheric dispersion modeling and downwind radiological plume mapping",
            "Statutory advice on public sheltering, evacuation, and medical decorporation protocols",
        ],
        statutory_authority="Australian Radiation Protection and Nuclear Safety Act 1998 (Cth)",
        official_website="https://www.arpansa.gov.au",
        legislation_url="https://www.legislation.gov.au/Details/C2016C00965",
        liaison_contact_role="Chief Radiation Health Scientist & Radiation Emergency Operations Director",
        preferred_brief_format="Radiological Emergency & Intervention Dose Assessment (Specific activity, plume footprint, TEDE dose projections).",
        relevant_threat_types=["radiological_dispersal", "nuclear_material"],
    ),
    AgencyIdentifier.ANSTO: AgencyProfile(
        id=AgencyIdentifier.ANSTO,
        full_name="Australian Nuclear Science and Technology Organisation (ANSTO)",
        portfolio="Department of Industry, Science and Resources",
        mandate_summary="Sovereign nuclear science institution operating Lucas Heights OPAL reactor, Australian Synchrotron, and national nuclear forensics laboratories.",
        key_responsibilities=[
            "High-resolution nuclear forensics, gamma spectrometry, and radioisotope mass spectrometry",
            "Nuclear provenance attribution and orphan source identification",
            "Production of nuclear medicine countermeasures and radiochemical research",
            "Specialist HAZMAT radiation safety survey and decontamination technical support",
        ],
        statutory_authority="Australian Nuclear Science and Technology Organisation Act 1987 (Cth)",
        official_website="https://www.ansto.gov.au",
        legislation_url="https://www.legislation.gov.au/Details/C2016C00966",
        liaison_contact_role="Head of Nuclear Forensics & Radioanalytical Sciences",
        preferred_brief_format="Nuclear Forensics & Isotopic Provenance Dossier (Photopeak resolution, isotopic ratios, material attribution).",
        relevant_threat_types=["radiological_dispersal", "nuclear_material"],
    ),
    AgencyIdentifier.ASNO: AgencyProfile(
        id=AgencyIdentifier.ASNO,
        full_name="Australian Safeguards and Non-Proliferation Office (ASNO)",
        portfolio="Department of Foreign Affairs and Trade",
        mandate_summary="Ensuring Australia's international non-proliferation and chemical/biological/nuclear treaty obligations are rigorously administered.",
        key_responsibilities=[
            "Administration of Nuclear Non-Proliferation (Safeguards) Act 1987",
            "IAEA Category 1 dangerous source accounting and illicit trafficking reporting",
            "OPCW chemical weapons convention declaration and verification",
            "Export controls over strategic nuclear, radiological, and dual-use materials",
        ],
        statutory_authority="Nuclear Non-Proliferation (Safeguards) Act 1987 (Cth)",
        official_website="https://www.dfat.gov.au/international-relations/security/asno",
        legislation_url="https://www.legislation.gov.au/Details/C2018C00286",
        liaison_contact_role="Director General of Safeguards & Non-Proliferation",
        preferred_brief_format="International Safeguards & Treaty Compliance Alert (IAEA reporting status, trafficking flags).",
        relevant_threat_types=["radiological_dispersal", "nuclear_material", "chemical_nerve_agent"],
    ),
    AgencyIdentifier.HOME_AFFAIRS: AgencyProfile(
        id=AgencyIdentifier.HOME_AFFAIRS,
        full_name="Department of Home Affairs (National Security & Critical Infrastructure)",
        portfolio="Department of Home Affairs",
        mandate_summary="Whole-of-nation counter-terrorism, critical infrastructure protection (SOCI Act), maritime border security, and national crisis coordination.",
        key_responsibilities=[
            "Security of Critical Infrastructure (SOCI Act) assets: ports, airports, water, hospitals",
            "National Counter-Terrorism Plan (NCTP) CBRN incident activation",
            "Australian Border Force (ABF) interdiction of illicit precursors and sources",
            "Coordination of National Security Committee of Cabinet (NSC) crisis deliberations",
        ],
        statutory_authority="Security of Critical Infrastructure Act 2018 (Cth)",
        official_website="https://www.homeaffairs.gov.au",
        legislation_url="https://www.legislation.gov.au/Details/C2022C00155",
        liaison_contact_role="National Counter-Terrorism Coordinator & Crisis Centre Director",
        preferred_brief_format="National Security & Critical Infrastructure Incident Brief (Infrastructure impact, interdiction status, NSC options).",
        relevant_threat_types=["chemical_nerve_agent", "chemical_toxin", "radiological_dispersal", "nuclear_material", "synthetic_engineered"],
    ),
}


def get_agency_profile(agency_id: AgencyIdentifier) -> AgencyProfile:
    if agency_id not in AUSTRALIAN_AGENCIES:
        raise KeyError(f"Agency {agency_id} not registered.")
    return AUSTRALIAN_AGENCIES[agency_id]
